extends:
  import: classic
  file: pipeline.yaml
agent:
  label: jenkins-go
  container: gcr.io/jenkinsxio/jx-cli
pipelines:
  release:
    pipeline:
      stages:
      - name: release
        agent:
          image: gcr.io/jenkinsxio/jx-cli
        options:
          containerOptions:
            env:
            - name: XDG_CONFIG_HOME
              value: "/builder/home"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        steps:
        - args:
          - release
          command: make
          dir: /workspace/source
          name: release
        - args:
          - admin
          - log
          - --sha-mode
          command: jx
          dir: /workspace/source
          name: log-apply

  pullRequest:
    pipeline:
      stages:
      - name: pr-checks
        agent:
          image: gcr.io/jenkinsxio/jx-cli
        steps:
        - args:
          - step
          - git
          - credentials
          command: jx
          dir: /workspace/source
          name: git-credentials
          image: gcr.io/jenkinsxio/builder-go
          env:
          - name: XDG_CONFIG_HOME
            value: /workspace/xdg_config
        - args:
          - pr
          command: make
          dir: /workspace/source
          name: pr
          env:
          - name: XDG_CONFIG_HOME
            value: /workspace/xdg_config
#        - args:
#          - --ignore-missing-schemas
#          - -d
#          - config-root
#          command: kubeval
#          dir: /workspace/source
#          image: garethr/kubeval:latest
#          name: kubeval
        # - args:
        #   - vet
        #   - --source-format
        #   - unstructured
        #   - --path
        #   - config-root
        #   command: nomos
        #   dir: /workspace/source
        #   image: gcr.io/config-management-release/nomos:v1.3.2-rc.20
        #   name: nomos-vet


