extends:
  import: classic
  file: javascript/pipeline.yaml
pipelines:
  environment:
    - name: DOCKER_ORG
      value: kubernetes
  pullRequest:
    build:
      steps:
      - sh: printenv
        name: print-env
      - sh: export VERSION="PR-$PULL_NUMBER" && skaffold build -f skaffold.yaml
        name: container-build
    postBuild:
      steps:
      - sh: export VERSION="PR-$PULL_NUMBER" && jx step post build --image $DOCKER_REGISTRY/$DOCKER_ORG/$APP_NAME:$VERSION && printenv
        name: post-build
  release:
    build:
      steps:
      - sh: export VERSION="$PULL_BASE_REF-latest" && skaffold build -f skaffold.yaml
        name: container-build
      - sh: export VERSION="$PULL_BASE_REF-latest" && jx step post build --image $DOCKER_REGISTRY/$DOCKER_ORG/$APP_NAME:$VERSION && printenv
        name: post-build
