extends:
  import: classic
  file: javascript/pipeline.yaml
pipelines:
  pullRequest:
    build:
      steps:
      - sh: export DOCKER_ORG='kubernetes'
        name: set-docker-org
      - sh: printenv
        name: print-env
      - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
        name: container-build
    postBuild:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/$DOCKER_ORG/$APP_NAME:$PREVIEW_VERSION
        name: post-build

  release:
    build:
      steps:
      - sh: export DOCKER_ORG='kubernetes'
        name: set-docker-org
      - sh: export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml
        name: container-build
      - sh: jx step post build --image $DOCKER_REGISTRY/$DOCKER_ORG/$APP_NAME:\$(cat VERSION)
        name: post-build
