extends:
  import: classic
  file: javascript/pipeline.yaml
pipelines:
  pullRequest:
    build:
      steps:
      - sh: echo "PR-$PULL_NUMBER"
        name: print-version
      - sh: export VERSION="PR-$PULL_NUMBER" && export DOCKER_ORG="kubernetes" && skaffold build -f skaffold.yaml
        name: container-build
    postBuild:
      steps:
      - sh: export VERSION="PR-$PULL_NUMBER" && export DOCKER_ORG="kubernetes" && jx step post build --image $DOCKER_REGISTRY/$DOCKER_ORG/$APP_NAME:$VERSION && printenv
        name: post-build
  release:
    build:
      steps:
      - sh: export VERSION="$PULL_BASE_REF-latest" && export DOCKER_ORG="kubernetes" && skaffold build -f skaffold.yaml
        name: container-build
      - sh: export VERSION="$PULL_BASE_REF-latest" && export DOCKER_ORG="kubernetes" && jx step post build --image $DOCKER_REGISTRY/$DOCKER_ORG/$APP_NAME:$VERSION && printenv
        name: post-build
