agent:
  image: "dockeronce.azurecr.io/jx/sonf-js:v12-latest"
  pipelines:
    post: {}
    pullRequest:
      pipeline:
        options:
          containerOptions:
            env:
            - name: DOCKER_CONFIG
              value: /home/jenkins/.docker/
            - name: DOCKER_REGISTRY
              valueFrom:
                configMapKeyRef:
                  key: docker.registry
                  name: jenkins-x-docker-registry
            - name: GIT_AUTHOR_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_AUTHOR_NAME
              value: jenkins-x-bot
            - name: GIT_COMMITTER_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_COMMITTER_NAME
              value: jenkins-x-bot
            - name: JENKINS_URL
              value: http://jenkins:8080
            - name: XDG_CONFIG_HOME
              value: /home/jenkins
            name: ""
            resources:
              limits:
                cpu: "2"
                memory: 2Gi
              requests:
                cpu: 400m
                memory: 512Mi
            securityContext:
              privileged: true
            volumeMounts:
            - mountPath: /home/jenkins
              name: workspace-volume
            - mountPath: /var/run/docker.sock
              name: docker-daemon
            - mountPath: /home/jenkins/.docker
              name: volume-0
          volumes:
          - emptyDir: {}
            name: workspace-volume
          - hostPath:
              path: /var/run/docker.sock
            name: docker-daemon
          - name: volume-0
            secret:
              secretName: jenkins-docker-cfg
        stages:
          - agent:
              image: ruby
            dir: /workspace/source
            name: from-build-pack
            steps:
            - args:
              - --cache=true
              - --cache-dir=/workspace
              - --context=/workspace/source
              - --dockerfile=/workspace/source/Dockerfile
              - --destination=dockeronce.azurecr.io/so-nagender/startup-with-node:${inputs.params.version}
              - --cache-repo=dockeronce.azurecr.io/todo/cache
              - --skip-tls-verify-registry=dockeronce.azurecr.io
              command: /kaniko/executor
              dir: /workspace/source
              image: gcr.io/kaniko-project/executor:v0.22.0
              name: build-container-build
            - command: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION && echo nagender
              dir: /workspace/source
              image: ruby
              name: postbuild-post-build
            - command: make preview
              dir: /workspace/source/charts/preview
              image: ruby
              name: promote-make-preview
            - command: jx preview --app $APP_NAME --dir ../..
              dir: /workspace/source/charts/preview
              image: ruby
              name: promote-jx-preview