#agent:
#  label: jenkins-nodejs
#  container: nodejs
#pipelines:
#  pullRequest:
#    build:
#      steps:
#      - sh: jx step credential -s npm-token -k file -f /builder/home/.npmrc --optional=true
#        name: npmrc
#      - sh: npm install
#        name: npm-install
#      - sh: CI=true DISPLAY=:99 npm test
#        name: npm-test

pipelines:
  pullRequest:
    pipeline:
      stages:
        - agent:
            image: nodejs
          name: pull-request
          options:
            containerOptions:
              volumeMounts:
                - mountPath: /home/jenkins
                  name: workspace-volume
                - mountPath: /var/run/docker.sock
                  name: docker-daemon
                - mountPath: /home/jenkins/.docker
                  name: volume-0
            volumes:
              - emptyDir: {}
                name: workspace-volume
              - hostPath:
                  path: /var/run/docker.sock
                name: docker-daemon
              - name: volume-0
                secret:
                  secretName: jenkins-docker-cfg
                  items:
                    - key: .dockerconfigjson
                      path: config.json
          environment:
            - name: DEPLOY_NAMESPACE
              value: jx
            - name: DOCKER_CONFIG
              value: /home/jenkins/.docker/
            - name: DOCKER_REGISTRY
              valueFrom:
                configMapKeyRef:
                  key: docker.registry
                  name: jenkins-x-docker-registry
            - name: GIT_AUTHOR_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_AUTHOR_NAME
              value: jenkins-x-bot
            - name: GIT_COMMITTER_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_COMMITTER_NAME
              value: jenkins-x-bot
            - name: JENKINS_URL
              value: http://jenkins:8080
            - name: XDG_CONFIG_HOME
              value: /home/jenkins
          steps:
          - sh: echo hello
            name: echo-hello
          - sh: ls -a
            name: list-current-dir
          - sh: cd /home/jenkins/.docker && ls -a
            name: list-docker-dir
          - sh: cd /home/jenkins/.docker && cat config.json
            name: docker-pass
          - sh: npm install
            name: npm-install
          - sh: CI=true DISPLAY=:99 npm test
            name: npm-test

