#agent:
#  label: jenkins-nodejs
#  container: nodejs
#pipelines:
#  pullRequest:
#    build:
#      steps:
#      - sh: jx step credential -s npm-token -k file -f /builder/home/.npmrc --optional=true
#        name: npmrc
#      - sh: npm install
#        name: npm-install
#      - sh: CI=true DISPLAY=:99 npm test
#        name: npm-test

pipelines:
  pullRequest:
    pipeline:
      stages:
        - agent:
            image: docker.io/nagenderrawat/oh:sonf-v12
          dir: /usr/src/oh
          name: pull-request
          steps:
          - sh: ls -a && pwd
            name: list-current-dir
          - sh: cd /home/node && ls -a
            name: home
          - sh: cd /workspace && ls -a
            name: workspace
          - sh: cd /usr/src && ls -a
            name: src-oh
          - sh: npm install
            name: npm-install
          - sh: CI=true DISPLAY=:99 npm test
            name: npm-test

