pipelines:
  post: {}
  pullRequest:
    pipeline:
      stages:
        - agent:
            image: "dockeronce.azurecr.io/jx/sonf-js:v12-latest"
          name: pr-release
          options:
            containerOptions:
              volumeMounts:
                - mountPath: /home/jenkins
                  name: workspace-volume
                - mountPath: /var/run/docker.sock
                  name: docker-daemon
                - mountPath: /home/jenkins/.docker
                  name: volume-0
                - mountPath: /tekton/home/.docker
                  name: volume-0
            volumes:
              - emptyDir: {}
                name: workspace-volume
              - hostPath:
                  path: /var/run/docker.sock
                name: docker-daemon
              - name: volume-0
                secret:
                  secretName: jenkins-docker-cfg
                  items:
                    - key: .dockerconfigjson
                      path: config.json
          environment:
            - name: DOCKER_CONFIG
              value: /home/jenkins/.docker/
            - name: DOCKER_REGISTRY
              valueFrom:
                configMapKeyRef:
                  key: docker.registry
                  name: jenkins-x-docker-registry
            - name: GIT_AUTHOR_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_AUTHOR_NAME
              value: jenkins-x-bot
            - name: GIT_COMMITTER_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_COMMITTER_NAME
              value: jenkins-x-bot
            - name: JENKINS_URL
              value: http://jenkins:8080
            - name: XDG_CONFIG_HOME
              value: /home/jenkins
          steps:
          - sh: echo "logging started bhai-nagender..."
            name: log-nagender
          - sh: jx step credential -s npm-token -k file -f /builder/home/.npmrc --optional=true
            name: npmrc
          - sh: npm install
            name: npm-install
          - sh: CI=true DISPLAY=:99 npm test
            name: npm-test
          - args:
            - --cache=true
            - --cache-dir=/workspace
            - --context=/workspace/source
            - --dockerfile=/workspace/source/Dockerfile
            - --destination=dockeronce.azurecr.io/so-nagender/startup-with-node:${inputs.params.version}
            - --cache-repo=dockeronce.azurecr.io/todo/cache
            - --skip-tls-verify-registry=dockeronce.azurecr.io
            command: /kaniko/executor
            image: gcr.io/kaniko-project/executor:v0.22.0
            name: build
          - command: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION && echo nagender
            name: post-build
