agent:
  label: jenkins-nodejs
  container: nodejs
pipelines:
  pullRequest:
    build:
      steps:
      - sh: jx step credential -s npm-token -k file -f /builder/home/.npmrc --optional=true
        name: npmrc
      - sh: npm install
        name: npm-install
      - sh: CI=true DISPLAY=:99 npm test
        name: npm-test