pipelineConfig:
  pipelines:
    pullRequest:
      pipeline:
        agent:
          image: gcr.io/jenkinsxio/builder-go
        environment:
          - name: DEPLOY_NAMESPACE
            value: jx
        stages:
          - name: release
            steps:
              - name: echo-hello
                sh: echo hello