#agent:
#  label: jenkins-nodejs
#  container: nodejs
#pipelines:
#  pullRequest:
#    build:
#      steps:
#      - sh: jx step credential -s npm-token -k file -f /builder/home/.npmrc --optional=true
#        name: npmrc
#      - sh: npm install
#        name: npm-install
#      - sh: CI=true DISPLAY=:99 npm test
#        name: npm-test

#pipelines:
#  pullRequest:
#    pipeline:
#      stages:
#        - agent:
#            image: docker.io/nagenderrawat/oh:sonf-v1 2
#          dir: /usr/src/oh
#          name: pull-request
#          steps:
#          - sh: ls -a && pwd
#            name: list-current-dir
#          - sh: cd ./env-tag
#            name: home
#          - sh: cd /workspace && ls -a
#            name: workspace
#          - sh: cd /usr/src && ls -a
#            name: src-oh
#          - sh: npm install
#            name: npm-install
#          - sh: CI=true DISPLAY=:99 npm test
#            name: npm-test
pipelines:
  post: {}
  pullRequest:
    pipeline:
      stages:
        - agent:
            image: dockeronce.azurecr.io/cloudbees/nodejs:sonf-v12-latest-user
          name: pr-release
          options:
            containerOptions:
              volumeMounts:
                - mountPath: /home/jenkins
                  name: workspace-volume
                - mountPath: /var/run/docker.sock
                  name: docker-daemon
                - mountPath: /home/jenkins/.docker
                  name: volume-0
            volumes:
              - emptyDir: {}
                name: workspace-volume
              - hostPath:
                  path: /var/run/docker.sock
                name: docker-daemon
              - name: volume-0
                secret:
                  secretName: jenkins-docker-cfg
                  items:
                  - key: .dockerconfigjson
                    path: config.json
          environment:
            - name: DOCKER_CONFIG
              value: /home/jenkins/.docker/
            - name: DOCKER_REGISTRY_ORG
              value: "kubernetes"
            - name: DOCKER_REGISTRY
              valueFrom:
                configMapKeyRef:
                  key: docker.registry
                  name: jenkins-x-docker-registry
            - name: GIT_AUTHOR_EMAIL
              value: nagender.rawat@scheduleonce.com
            - name: GIT_AUTHOR_NAME
              value: jenkins-x-bot
            - name: GIT_COMMITTER_EMAIL
              value: nagender.rawat@scheduleonce.com
            - name: GIT_COMMITTER_NAME
              value: jenkins-x-bot
          steps:
          - sh: echo "logging started bhai-nagender..."
            name: log-nagender
          - sh: node -v
            name: node-version
          - sh: npm install
            name: npm-install
          - sh: CI=true DISPLAY=:99 npm test
            name: npm-test
          - args:
            - --cache=true
            - --cache-dir=/workspace
            - --context=/workspace/source
            - --dockerfile=/workspace/source/Dockerfile
            - --destination=dockeronce.azurecr.io/${DOCKER_REGISTRY_ORG}/${APP_NAME}:PR-${PULL_NUMBER}
            - --cache-repo=dockeronce.azurecr.io/todo/cache
            - --skip-tls-verify-registry=dockeronce.azurecr.io
            command: /kaniko/executor
            image: gcr.io/kaniko-project/executor:v1.0.0
            name: build

